version: "3.9"


services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypwdfordeals
    ports:
      - '5432:5432'
    expose:
      - 5432
  deals:
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db:db


